In [1]:
# show distribution of FP types
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

file = 'data/mskcc/metadata.csv'
df = pd.read_csv(file)
df['fitzpatrick_skin_type'].value_counts()

fitzpatrick_skin_type
II     950
V      813
III    794
I      789
IV     783
VI     750
Name: count, dtype: int64

In [3]:
df['image_type'].value_counts()

image_type
dermoscopic           3678
clinical: close-up    1201
Name: count, dtype: int64

In [4]:
# check value counts for each image type
for image_type in df['image_type'].unique():
    print(f"Image type: {image_type}")
    print(df[df['image_type'] == image_type]['fitzpatrick_skin_type'].value_counts())
    print()

Image type: dermoscopic
fitzpatrick_skin_type
II     713
V      614
I      598
III    595
IV     585
VI     573
Name: count, dtype: int64

Image type: clinical: close-up
fitzpatrick_skin_type
II     237
V      199
III    199
IV     198
I      191
VI     177
Name: count, dtype: int64

In [7]:
df[['isic_id', 'fitzpatrick_skin_type']].head()

        isic_id fitzpatrick_skin_type
0  ISIC_0077599                    IV
1  ISIC_0082910                     V
2  ISIC_0086394                    II
3  ISIC_0087198                     V
4  ISIC_0087357                   III

In [8]:
scin_labels = 'data/scin/dataset/scin_labels.csv'
df_scin = pd.read_csv(scin_labels)
df_scin.head()

,case_id,dermatologist_gradable_for_skin_condition_1,dermatologist_gradable_for_skin_condition_2,dermatologist_gradable_for_skin_condition_3,dermatologist_skin_condition_on_label_name,dermatologist_skin_condition_confidence,weighted_skin_condition_label,dermatologist_gradable_for_fitzpatrick_skin_type_1,dermatologist_gradable_for_fitzpatrick_skin_type_2,dermatologist_gradable_for_fitzpatrick_skin_type_3,dermatologist_fitzpatrick_skin_type_label_1,dermatologist_fitzpatrick_skin_type_label_2,dermatologist_fitzpatrick_skin_type_label_3,gradable_for_monk_skin_tone_india,gradable_for_monk_skin_tone_us,monk_skin_tone_label_india,monk_skin_tone_label_us
0,-1000600354148496558,DEFAULT_YES_IMAGE_QUALITY_SUFFICIENT,NaN,NaN,"['Inflicted skin lesions', 'Eczema', 'Irritant...","[4, 4, 3]","{'Inflicted skin lesions': 0.41, 'Eczema': 0.4...",YES,NaN,NaN,FST2,NaN,NaN,True,True,2.0,1.0
1,-1002039107727665188,DEFAULT_YES_IMAGE_QUALITY_SUFFICIENT,NaN,NaN,"['Prurigo nodularis', 'Actinic Keratosis', 'SC...","[4, 3, 4]","{'Prurigo nodularis': 0.41, 'SCC/SCCIS': 0.41,...",YES,NaN,NaN,FST1,NaN,NaN,True,True,3.0,3.0
2,-1003358831658393077,DEFAULT_YES_IMAGE_QUALITY_SUFFICIENT,NaN,NaN,"['Impetigo', 'Herpes Zoster', 'Bullous dermati...","[2, 1, 1]","{'Impetigo': 0.55, 'Herpes Zoster': 0.23, 'Bul...",YES,NaN,NaN,FST4,NaN,NaN,True,True,3.0,4.0
3,-1003826561155964328,NO_IMAGE_QUALITY_INSUFFICIENT,NaN,NaN,[],[],{},NO,NaN,NaN,NaN,NaN,NaN,True,True,2.0,4.0
4,-1003844406100696311,DEFAULT_YES_IMAGE_QUALITY_SUFFICIENT,NaN,NaN,"['Lichen planus/lichenoid eruption', 'Follicul...","[1, 1, 1]","{'Lichen planus/lichenoid eruption': 0.33, 'Fo...",YES,NaN,NaN,FST1,NaN,NaN,True,True,1.0,1.0